"""M6.6 — the §5.7 evidence pack, generated from a paper-run decision journal.

This proves the pack generator against real journal rows in Postgres, exactly as it will run in
production: entries are written through the real `Journal` (which stores evidence content-addressed
and reads back through the same query surface the pack uses), and the pack is then generated by
reading only those rows. The three M6.6 acceptance criteria are each proved here:

1. **A pack generates from the paper run with every §5.7 section populated.** A faithful paper-run
   journal — SIP instalments parked (A7), a tactical deployment, a T0 heartbeat every day, T1
   reviews with token spend and break-condition verdicts, an A8 `RAIL_BLOCK`, a `SKIPPED_DATA_RED`
   data-red day, and a core exit that books a realized gain — is written for the reference case, and
   `generate_pack` produces an `EvidencePack` with all seven §5.7 sections populated.

2. **Every number traces to journal entries (no separate accounting).** Each figure the pack
   attributes to the case's activity is recomputed *independently* here, straight from
   `Journal.count`/`Journal.entries`, and asserted equal to the pack's — turnover, tax events, cost
   burn, rail blocks, data-red skips, the decision verdicts, and the SIP cashflow stream that drives
   the return. The pack keeps no ledger the journal does not.

3. **The rail-breach count is a bug indicator, not a neutral metric.** The clean run's rail section
   reads CLEAN with zero breaches and its rendered text calls a breach a bug against invariant #6;
   a second case whose journal carries a breach that reached the book flips the verdict to
   BUGS_PRESENT and the render to a defect warning. `RAIL_BLOCK` lines (rails *working*) are counted
   as context, never as breaches.

The entries mirror the payloads the M5 loop's real writers emit — A7's park
(`source_SIP_INSTALMENT`/`shares`/`price`), its deploy (`deployed_inr`), and A8's block (`rails`) —
so the pack's extraction is exercised against the real journal shape, not a bespoke one. The
decision journal and evidence store are the real Postgres/lake ones, so this needs the docker
postgres (`make up`) and skips loudly if unreachable, as `test_journal.py` and
`test_paper_run_10_sessions.py` do. Time is frozen and injected; no network is touched.
"""

from __future__ import annotations

import os
from collections.abc import Iterator
from dataclasses import replace
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Final

import psycopg
import pytest

from analyst.journal import (
    Actor,
    Decision,
    EvidencePack,
    EvidenceStore,
    Journal,
    JournalFilter,
    NavPoint,
    PackTrigger,
    PackValuation,
    Sleeve,
    generate_pack,
    render_markdown,
)
from analyst.journal.evidence import EvidenceBundle, EvidenceItem, EvidenceKind
from analyst.journal.models import BreakConditionEvaluation, JournalEntry, TokenSpend, Verdict
from dataplatform.clock import IST, FrozenClock
from dataplatform.config import Settings
from dataplatform.ingest.indices import TriPoint, TriSeries
from dataplatform.store.db import connect, connection, with_dbname
from dataplatform.store.migrate import migrate

pytestmark = pytest.mark.integration

#: Pid-suffixed so concurrent build agents do not drop each other's scratch DB (cf test_migrations).
SCRATCH_DB: Final = f"trading_m6_6_evidence_pack_{os.getpid()}"

CASE_ID: Final = "ai-robotics-ref"
BREACH_CASE_ID: Final = "breach-demo"

#: The pack window and the sessions the paper run writes into it. Two SIP instalments land inside it
#: (2026-08-03 and 2026-09-01), so the return is struck on two pay-ins plus the terminal NAV mark.
WINDOW_START: Final = date(2026, 8, 1)
WINDOW_END: Final = date(2026, 9, 30)
SIP_1: Final = date(2026, 8, 3)
DEPLOY_DATE: Final = date(2026, 8, 10)
T1_INTACT_DATE: Final = date(2026, 8, 12)
DATA_RED_DATE: Final = date(2026, 8, 20)
SIP_2: Final = date(2026, 9, 1)
RAIL_BLOCK_DATE: Final = date(2026, 9, 5)
T1_BROKEN_DATE: Final = date(2026, 9, 10)
EXIT_DATE: Final = date(2026, 9, 12)
AS_OF: Final = date(2026, 9, 30)

#: A distinct, earlier wall clock for the writes, so the run's `ts` values are unambiguous.
RUN_AT: Final = datetime(2026, 9, 30, 18, 30, tzinfo=IST)

DEPLOY_ISIN: Final = "INE100A01010"
INTACT_ISIN: Final = "INE200B01020"
RAIL_ISIN: Final = "INE300C01030"
EXIT_ISIN: Final = "INE400D01040"
PARKING_ISIN: Final = "INE500E01050"

SIP_AMOUNT: Final = Decimal("10000")
DEPLOY_VALUE: Final = Decimal("10000")
EXIT_VALUE: Final = Decimal("15000")
EXIT_GAIN: Final = Decimal("3000")
EXIT_CHARGES: Final = Decimal("52.50")

T1_TOKENS: Final = TokenSpend(tokens_in=1200, tokens_out=300, cost_inr=Decimal("0.85"))
T2_TOKENS: Final = TokenSpend(tokens_in=4000, tokens_out=900, cost_inr=Decimal("2.40"))
STUB_MODEL: Final = "stub-model"


# ── valuation marks (the only non-journal inputs the pack takes) ──────────────────────────────────


def _tri(slug: str, name: str, levels: dict[date, str]) -> TriSeries:
    """A published TRI series from a date→level table."""
    return TriSeries(
        index_slug=slug,
        index_name=name,
        method="published",
        points=tuple(
            TriPoint(
                index_slug=slug,
                index_name=name,
                as_of=as_of,
                tri_value=Decimal(level),
                method="published",
            )
            for as_of, level in sorted(levels.items())
        ),
    )


def _valuation() -> PackValuation:
    """The NAV series (with a real drawdown) and the two benchmark legs.

    NAV dips from ₹1,05,000 to ₹98,000 mid-run before recovering to ₹1,10,000, so the drawdown
    profile has a genuine peak-to-trough to report. The benchmark levels are chosen so the two
    benchmark XIRRs differ from the portfolio's — the excess figures are non-trivial.
    """
    nav = (
        NavPoint(as_of=SIP_1, nav_inr=Decimal("10000")),
        NavPoint(as_of=DEPLOY_DATE, nav_inr=Decimal("10500")),
        NavPoint(as_of=DATA_RED_DATE, nav_inr=Decimal("9800")),
        NavPoint(as_of=SIP_2, nav_inr=Decimal("20800")),
        NavPoint(as_of=AS_OF, nav_inr=Decimal("21500")),
    )
    benchmark = _tri(
        "nifty50_tri",
        "NIFTY 50 TRI",
        {WINDOW_START: "20000", SIP_2: "20800", AS_OF: "21200"},
    )
    theme = _tri(
        "robotics_proxy",
        "Robotics theme proxy",
        {WINDOW_START: "1000", SIP_2: "1010", AS_OF: "1015"},
    )
    return PackValuation(nav_series=nav, benchmark=benchmark, theme=theme)


# ── the paper-run journal (real Journal writes, payloads matching the M5 loop's writers) ──────


def _heartbeat_bundle(trading_date: date) -> EvidenceBundle:
    """A minimal but valid T0 evidence bundle — a heartbeat needs one (invariant #9)."""
    return EvidenceBundle(
        case_id=CASE_ID,
        trading_date=trading_date,
        actor=Actor.T0,
        items=(
            EvidenceItem(
                kind=EvidenceKind.STATUS,
                source="status_api",
                label="sync",
                text="all core datasets PUBLISHED and quality-green",
            ),
        ),
    )


def _write_paper_run(journal: Journal) -> None:
    """Write a faithful paper-run journal for the reference case (acceptance 1's substrate).

    The entries mirror what the M5 daily loop's real writers emit — the payload keys are A7's and
    A8's, verbatim — so the pack reads the production journal shape. Every trading date carries at
    least a heartbeat (invariant #9); the eventful days add the trade, review, block or skip.
    """
    # A heartbeat every session in the window's active range (invariant #9).
    for day in (SIP_1, DEPLOY_DATE, T1_INTACT_DATE, SIP_2, RAIL_BLOCK_DATE, T1_BROKEN_DATE):
        journal.heartbeat(_heartbeat_bundle(day), actor=Actor.T0)

    # SIP instalment #1: parked in the liquid ETF the same session (A7 park payload).
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=SIP_1,
            case_id=CASE_ID,
            actor=Actor.EXEC,
            decision=Decision.BUY,
            isin=PARKING_ISIN,
            sleeve=Sleeve.CASH,
            rationale="parking the SIP instalment in the liquid ETF the same session (§5.6)",
            payload={
                "source_SIP_INSTALMENT": str(SIP_AMOUNT),
                "shares": "10",
                "price": "1000",
                "residual_cash": "0",
            },
        )
    )
    # Tactical deployment of the parked cash (A7 deploy payload).
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=DEPLOY_DATE,
            case_id=CASE_ID,
            actor=Actor.T2,
            decision=Decision.BUY,
            isin=DEPLOY_ISIN,
            sleeve=Sleeve.TACTICAL,
            rationale="deploy the parked SIP instalment on a tactical opportunity (§5.6)",
            payload={"deployed_inr": str(DEPLOY_VALUE), "sleeve": Sleeve.TACTICAL.value},
        )
    )
    # A T1 review that finds the thesis intact — a HOLD carrying its verdict and its token cost.
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=T1_INTACT_DATE,
            case_id=CASE_ID,
            actor=Actor.T1,
            decision=Decision.HOLD,
            isin=INTACT_ISIN,
            model=STUB_MODEL,
            tokens=T1_TOKENS,
            break_conditions_evaluated=(
                BreakConditionEvaluation(
                    id="BC1", verdict=Verdict.INTACT, observed="delivery volumes holding"
                ),
            ),
        )
    )
    # A data-red day: the loop reads /status/sync, finds it not green, and does not trade.
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=DATA_RED_DATE,
            case_id=CASE_ID,
            actor=Actor.SYSTEM,
            decision=Decision.SKIPPED_DATA_RED,
            rationale="bhavcopy did not publish; /status/sync not green, no trading (inv #10)",
        )
    )
    # SIP instalment #2, a month later.
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=SIP_2,
            case_id=CASE_ID,
            actor=Actor.EXEC,
            decision=Decision.BUY,
            isin=PARKING_ISIN,
            sleeve=Sleeve.CASH,
            rationale="parking the second SIP instalment in the liquid ETF (§5.6)",
            payload={
                "source_SIP_INSTALMENT": str(SIP_AMOUNT),
                "shares": "10",
                "price": "1000",
                "residual_cash": "0",
            },
        )
    )
    # An oversized order refused by A8 — a RAIL_BLOCK (rails working, not a breach).
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=RAIL_BLOCK_DATE,
            case_id=CASE_ID,
            actor=Actor.RAILS,
            decision=Decision.RAIL_BLOCK,
            isin=RAIL_ISIN,
            rationale="order value exceeds the ratified per-order cap; refused (invariant #6)",
            payload={"rails": "MAX_ORDER_VALUE"},
        )
    )
    # A T2 review that finds a break condition BROKEN — escalated, with its token cost.
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=T1_BROKEN_DATE,
            case_id=CASE_ID,
            actor=Actor.T2,
            decision=Decision.ESCALATE,
            isin=EXIT_ISIN,
            model=STUB_MODEL,
            tokens=T2_TOKENS,
            rationale="BC2 broken: order book collapsed two quarters running; escalating for exit",
            break_conditions_evaluated=(
                BreakConditionEvaluation(
                    id="BC2", verdict=Verdict.BROKEN, observed="revenue guidance withdrawn"
                ),
            ),
        )
    )
    # The core exit that followed the BROKEN verdict — books a realized gain (a tax event). The
    # value/gain/charges/holding-period keys are what a value-carrying exit records; see the M6.6
    # backlog note on making A6's SELL entries carry these so this is journal-reconstructable.
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=EXIT_DATE,
            case_id=CASE_ID,
            actor=Actor.T2,
            decision=Decision.SELL,
            isin=EXIT_ISIN,
            sleeve=Sleeve.CORE,
            rationale="exit on the BROKEN thesis over the ratified menu (§5.5, decision #4)",
            break_conditions_evaluated=(
                BreakConditionEvaluation(
                    id="BC2", verdict=Verdict.BROKEN, observed="thesis broken"
                ),
            ),
            payload={
                "value_inr": str(EXIT_VALUE),
                "realized_gain_inr": str(EXIT_GAIN),
                "charges_inr": str(EXIT_CHARGES),
                "holding_period": "SHORT",
            },
        )
    )


def _write_breach_case(journal: Journal) -> None:
    """A second case whose journal carries a rail breach that reached the book (acceptance 3).

    One SIP pay-in (so a pack can be generated at all) and one BUY flagged `rail_breach` — a trade
    that violated a cap the rails should have stopped. This is the defect the pack must surface as a
    bug, not a neutral event.
    """
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=SIP_1,
            case_id=BREACH_CASE_ID,
            actor=Actor.EXEC,
            decision=Decision.BUY,
            isin=PARKING_ISIN,
            sleeve=Sleeve.CASH,
            rationale="parking the SIP instalment (§5.6)",
            payload={"source_SIP_INSTALMENT": str(SIP_AMOUNT), "shares": "10", "price": "1000"},
        )
    )
    journal.append(
        JournalEntry(
            ts=RUN_AT,
            trading_date=DEPLOY_DATE,
            case_id=BREACH_CASE_ID,
            actor=Actor.EXEC,
            decision=Decision.BUY,
            isin=DEPLOY_ISIN,
            sleeve=Sleeve.TACTICAL,
            rationale="a position that breached the per-position cap but was filled — a rails bug",
            payload={
                "deployed_inr": "50000",
                "rail_breach": "true",
                "rails": "MAX_POSITION",
            },
        )
    )


# ── database fixtures (the scratch-DB pattern from test_journal.py / test_paper_run) ──────────


def _settings_for(dbname: str) -> Settings:
    return Settings(database_url=with_dbname(Settings().database_url, dbname))


def _insert_case(conn: psycopg.Connection, case_id: str, title: str) -> None:
    """A minimal ACTIVE/PAPER case_ row — decision_journal.case_id is a foreign key onto it."""
    conn.execute(
        "INSERT INTO case_ (case_id, title, state, funding_mode, theme, created_at, updated_at) "
        "VALUES (%s, %s, 'ACTIVE', 'PAPER', %s, %s, %s)",
        (case_id, title, "ai & robotics", RUN_AT, RUN_AT),
    )


@pytest.fixture(scope="session")
def pack_settings(tmp_path_factory: pytest.TempPathFactory) -> Iterator[Settings]:
    """An empty scratch database with the schema applied and the paper-run journal committed."""
    admin = _settings_for("postgres")
    try:
        conn = connect(admin, autocommit=True)
    except psycopg.OperationalError as error:  # pragma: no cover - environment, not logic
        pytest.skip(f"postgres is not reachable — run `make up` first: {error}")
    try:
        conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{SCRATCH_DB}"')
    finally:
        conn.close()

    scratch = _settings_for(SCRATCH_DB)
    migrate(scratch, clock=FrozenClock(RUN_AT))

    evidence_root = tmp_path_factory.mktemp("pack_evidence")
    with connection(scratch) as conn:
        _insert_case(conn, CASE_ID, "AI & robotics reference case")
        _insert_case(conn, BREACH_CASE_ID, "Rail-breach demonstration case")
        journal = Journal(
            conn, clock=FrozenClock(RUN_AT), evidence=EvidenceStore(root=evidence_root)
        )
        _write_paper_run(journal)
        _write_breach_case(journal)
        conn.commit()

    yield scratch

    conn = connect(admin, autocommit=True)
    try:
        conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
    finally:
        conn.close()


@pytest.fixture
def pack_journal(pack_settings: Settings, tmp_path: Path) -> Iterator[Journal]:
    """A read connection onto the committed run, for generating and cross-checking packs."""
    with connection(pack_settings) as conn:
        yield Journal(conn, clock=FrozenClock(RUN_AT), evidence=EvidenceStore(root=tmp_path))


@pytest.fixture
def pack(pack_journal: Journal) -> EvidencePack:
    """The evidence pack for the reference case's paper run — the object under test."""
    return generate_pack(
        pack_journal,
        case_id=CASE_ID,
        window_start=WINDOW_START,
        window_end=WINDOW_END,
        valuation=_valuation(),
        generated_at=RUN_AT,
        trigger=PackTrigger.GRADUATION,
    )


# ── acceptance 1: a pack generates from the paper run with every §5.7 section populated ────────


def test_pack_generates_with_every_section_populated(pack: EvidencePack) -> None:
    """All seven §5.7 sections are present and carry real content from the paper run."""
    assert pack.case_id == CASE_ID
    assert pack.trigger is PackTrigger.GRADUATION
    assert pack.window_start == WINDOW_START and pack.window_end == WINDOW_END
    assert pack.entries_reviewed > 0

    # 1. Returns vs both benchmarks (XIRR since SIP), on two pay-ins plus the terminal mark.
    assert pack.returns.cashflow_count == 2
    assert pack.returns.first_sip_date == SIP_1
    assert pack.returns.total_invested_inr == SIP_AMOUNT * 2
    assert pack.returns.terminal_value_inr == Decimal("21500")
    # Three distinct return figures were struck (portfolio vs both benchmarks).
    assert pack.returns.portfolio_xirr != pack.returns.benchmark_xirr
    assert pack.returns.theme_xirr != pack.returns.benchmark_xirr

    # 2. Drawdown profile — a genuine peak-to-trough on the NAV marks.
    assert pack.drawdown.max_drawdown_pct > Decimal("0")
    assert pack.drawdown.peak_date == DEPLOY_DATE and pack.drawdown.trough_date == DATA_RED_DATE

    # 3. Rail breaches — present, and clean on this run.
    assert pack.rail_breaches.breach_count == 0
    assert pack.rail_breaches.rail_blocks == 1

    # 4. Decision review — T1/T2 verdicts, with the exit that followed the BROKEN one.
    assert len(pack.decision_review.reviews) == 2
    broken = [r for r in pack.decision_review.reviews if r.verdict == "BROKEN"]
    assert len(broken) == 1 and broken[0].subsequent_action == "SELL"

    # 5. Turnover + tax by sleeve — every traded sleeve, and the realized-gain tax event.
    sleeves = {s.sleeve for s in pack.turnover_tax.by_sleeve}
    assert sleeves == {Sleeve.CASH, Sleeve.TACTICAL, Sleeve.CORE}
    assert len(pack.turnover_tax.tax_events) == 1
    assert pack.turnover_tax.untraceable_trades == ()

    # 6. Token / cost burn — the two model-calling tiers.
    assert {t.actor for t in pack.cost_burn.by_tier} == {Actor.T1, Actor.T2}
    assert pack.cost_burn.total_cost_inr == T1_TOKENS.cost_inr + T2_TOKENS.cost_inr

    # 7. Data-quality skips — the one data-red day.
    assert pack.data_quality.data_red_skips == 1
    assert pack.data_quality.skipped_dates == (DATA_RED_DATE,)


# ── acceptance 2: every number traces to journal entries (no separate accounting) ─────────────────


def test_every_number_traces_to_journal_entries(pack: EvidencePack, pack_journal: Journal) -> None:
    """Each figure is recomputed from the journal and matches the pack — no second ledger."""
    window = JournalFilter(case_id=CASE_ID, start=WINDOW_START, end=WINDOW_END)

    # Rail blocks: the pack's count equals the journal's count of RAIL_BLOCK rows.
    assert pack.rail_breaches.rail_blocks == pack_journal.count(
        replace(window, decision=Decision.RAIL_BLOCK)
    )

    # Data-red skips: the pack's count equals the journal's count of SKIPPED_DATA_RED rows.
    assert pack.data_quality.data_red_skips == pack_journal.count(
        replace(window, decision=Decision.SKIPPED_DATA_RED)
    )

    # Cost burn: recomputed by summing TokenSpend over every entry that carried one.
    all_entries = pack_journal.entries(window)
    expected_cost = sum(
        (e.tokens.cost_inr for e in all_entries if e.tokens is not None), Decimal("0")
    )
    expected_in = sum(e.tokens.tokens_in for e in all_entries if e.tokens is not None)
    assert pack.cost_burn.total_cost_inr == expected_cost
    assert pack.cost_burn.total_tokens_in == expected_in

    # SIP cashflows: the invested total equals the sum of source_SIP_INSTALMENT over park entries.
    buys = pack_journal.entries(replace(window, decision=Decision.BUY))
    expected_invested = sum(
        (
            Decimal(e.payload["source_SIP_INSTALMENT"])
            for e in buys
            if "source_SIP_INSTALMENT" in e.payload
        ),
        Decimal("0"),
    )
    assert pack.returns.total_invested_inr == expected_invested

    # Turnover: TACTICAL turnover equals the deploy value read from its own journal entry.
    tactical = next(s for s in pack.turnover_tax.by_sleeve if s.sleeve is Sleeve.TACTICAL)
    (deploy_entry,) = [e for e in buys if e.isin == DEPLOY_ISIN and e.sleeve is Sleeve.TACTICAL]
    assert tactical.buy_value_inr == Decimal(deploy_entry.payload["deployed_inr"])

    # Tax event: the realized gain equals what the SELL entry itself recorded.
    sells = pack_journal.entries(replace(window, decision=Decision.SELL))
    (sell_entry,) = sells
    (tax_event,) = pack.turnover_tax.tax_events
    assert tax_event.realized_gain_inr == Decimal(sell_entry.payload["realized_gain_inr"])
    assert tax_event.isin == sell_entry.isin

    # Entries reviewed: the pack read exactly the window's journal rows, nothing else.
    assert pack.entries_reviewed == len(all_entries)


# ── acceptance 3: the rail-breach count is a bug indicator, not a neutral metric ──────────────────


def test_rail_breach_count_is_presented_as_a_bug_indicator(pack: EvidencePack) -> None:
    """A clean run reads CLEAN; the rendered text frames a breach as a bug against invariant #6."""
    assert pack.rail_breaches.is_clean
    assert pack.rail_breaches.verdict == "CLEAN"

    rendered = render_markdown(pack)
    rail_lines = rendered.lower()
    assert "target" in rail_lines and "zero" in rail_lines
    assert "bug" in rail_lines  # a breach is called a bug, not a neutral risk event
    assert "invariant #6" in rendered
    # A RAIL_BLOCK (rails working) must not be miscounted as a breach.
    assert "0 — verdict clean" in rail_lines


def test_a_breach_that_reached_the_book_flips_the_verdict_to_bug(pack_journal: Journal) -> None:
    """The second case's filled breach is surfaced as BUGS_PRESENT, with a defect warning."""
    breach_pack = generate_pack(
        pack_journal,
        case_id=BREACH_CASE_ID,
        window_start=WINDOW_START,
        window_end=WINDOW_END,
        valuation=_valuation(),
        generated_at=RUN_AT,
        trigger=PackTrigger.MONTHLY,
    )
    assert breach_pack.rail_breaches.breach_count == 1
    assert not breach_pack.rail_breaches.is_clean
    assert breach_pack.rail_breaches.verdict == "BUGS_PRESENT"

    rendered = render_markdown(breach_pack)
    assert "BUGS_PRESENT" in rendered
    assert "defect" in rendered.lower()
    assert "MAX_POSITION" in rendered  # the breached cap is named for investigation


# ── readable in ten minutes: the render carries every section, top to bottom ──────────────────────


def test_rendered_pack_is_a_single_readable_document(pack: EvidencePack) -> None:
    """render_markdown produces one document with all seven §5.7 section headers, in order."""
    rendered = render_markdown(pack)
    for heading in (
        "## 1. Returns vs benchmarks",
        "## 2. Drawdown profile",
        "## 3. Rail breaches",
        "## 4. Decision review",
        "## 5. Turnover & tax events by sleeve",
        "## 6. Token / cost burn",
        "## 7. Data-quality skips",
    ):
        assert heading in rendered, f"missing section: {heading}"
    # No unfilled template placeholders leaked into the render.
    assert "$" not in rendered
    assert CASE_ID in rendered


def test_empty_window_is_a_loud_refusal(pack_journal: Journal) -> None:
    """A window with no entries raises rather than emitting a hollow pack (CLAUDE.md: fail loud)."""
    from analyst.journal import EvidencePackError

    with pytest.raises(EvidencePackError):
        generate_pack(
            pack_journal,
            case_id=CASE_ID,
            window_start=date(2030, 1, 1),
            window_end=date(2030, 12, 31),
            valuation=_valuation(),
            generated_at=RUN_AT,
        )


if __name__ == "__main__":  # pragma: no cover - convenience for a direct run
    raise SystemExit(pytest.main([__file__, "-q"]))
