-- 0003_scheduler — the scheduled-job history (EXECUTION_PLAN.md §8.1, task M0.6).
--
-- The heartbeat table this job history sits beside is `scheduler_heartbeat`, created by
-- 0002_status_surface.sql: /health could not exist without a table to read, so M0.5 declared it
-- and M0.6 writes it. This file adds the other half — the history the heartbeat is a summary of.
--
-- Why both. `scheduler_heartbeat` holds exactly one row per logical scheduler, upserted, and
-- answers "is it alive right now". `job_run` holds one row per attempt and answers "what has it
-- actually done", which is a different question and the only one that can be asked after the
-- fact. Deriving either from the other loses something real: the process tick that proves the
-- scheduler is alive on a day when nothing is due is not a run, and a run that was skipped
-- because another process held the lock is not a heartbeat.
--
-- Conventions are 0001_init's: timestamptz for instants, text + CHECK for enumerations, no
-- BEGIN/COMMIT and no IF NOT EXISTS — the runner wraps this file in one transaction and it runs
-- exactly once against a database.
--
-- Ownership: commented `D5` because GET /health and the status API (§4.4) are what surface it,
-- and the schema's convention is that a table names the plan module allowed to read and write it.
-- The scheduler is infrastructure and carries no D/A/X number of its own; `dataplatform/scheduler`
-- is the only writer.

-- ── D5 · scheduled job history ──────────────────────────────────────────────────────────────

CREATE TABLE job_run (
    run_id      uuid        PRIMARY KEY,
    job_name    text        NOT NULL,
    state       text        NOT NULL CHECK (state IN (
                                'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT', 'SKIPPED_LOCKED')),
    instance    text        NOT NULL,
    started_at  timestamptz NOT NULL,
    finished_at timestamptz,
    error       text,
    CONSTRAINT job_run_running_iff_unfinished
        CHECK ((state = 'RUNNING') = (finished_at IS NULL)),
    CONSTRAINT job_run_error_needs_a_failure
        CHECK (error IS NULL OR state IN ('FAILED', 'TIMED_OUT'))
);
COMMENT ON TABLE job_run IS
    'D5 · One row per attempt to run a registered job, written by dataplatform.scheduler.runner. '
    'An attempt that never ran because another process held the job''s advisory lock is recorded '
    'too, as SKIPPED_LOCKED: a job that silently did not run must not be indistinguishable from '
    'a day on which nothing was scheduled, which is the whole reason the lock is observable.';
COMMENT ON COLUMN job_run.run_id IS
    'Generated by the runner before the row is written, so the run id in the structured log of a '
    'process that died mid-job still identifies the row its RUNNING state was left in.';
COMMENT ON COLUMN job_run.instance IS
    'host:pid of the process that made the attempt. The advisory lock guarantees only one of two '
    'processes runs a given job; this column is how an operator sees which one won.';
COMMENT ON COLUMN job_run.state IS
    'TIMED_OUT means the function returned but overran its registered budget — the runner reports '
    'the overrun, it does not kill the job (dataplatform/scheduler/runner.py).';

CREATE INDEX job_run_by_job ON job_run (job_name, started_at DESC);
CREATE INDEX job_run_unfinished ON job_run (job_name, started_at) WHERE state = 'RUNNING';
